In [2]:
import pandas as pd

df_requisicao = pd.read_csv('data/Evah/OMNI_DADOS_REQUISICAO.csv', encoding='latin1')

C:\Users\JoaoC\AppData\Local\Temp\ipykernel_39900\853523274.py:3: DtypeWarning: Columns (17) have mixed types. Specify dtype option on import or set low_memory=False.
  df_requisicao = pd.read_csv('data/Evah/OMNI_DADOS_REQUISICAO.csv', encoding='latin1')

In [5]:
df_requisicao.describe(include='all')

,ID_REQUISICAO,DT_ATUALIZACAO,ID_BENEFICIARIO,ID_PRESTADOR,ID_PROFISSIONAL,DS_STATUS_REQUISICAO,DT_REQUISICAO,DT_FIM_ANALISE,DS_CBO_PROFISSIONAL,DS_TIPO_GUIA,DS_CARATER_ATENDIMENTO,DS_TIPO_INTERNACAO,DS_REGIME_INTERNACAO,DS_TIPO_ACOMODACAO,DS_TIPO_SADT,DS_TIPO_CONSULTA,ID_GUIA_PRINCIPAL,DT_ENTRADA_HOSPITAL
count,1.132997e+06,1132997,1.132997e+06,1.132938e+06,1.132954e+06,1132997,1132997,1132671,1131786,1132997,1132997,42793,42791,41547,613775,656994,3.567500e+04,27066
unique,NaN,504,NaN,NaN,NaN,4,488,502,89,4,2,5,3,36,14,4,NaN,639
top,NaN,11/09/23,NaN,NaN,NaN,Aprovada,18/09/23,09/04/24,Médico cardiologista,Guia de solicitação SP/SADT,Eletiva,Clínica,Hospitalar,ENFERMARIA DE 3 LEITOS,Exame,Primeira consulta,NaN,22/07/24
freq,NaN,6397,NaN,NaN,NaN,1055683,3956,4727,156593,635569,946909,23628,40841,27862,360606,362238,NaN,141
mean,4.157825e+07,NaN,1.348259e+05,1.297902e+03,1.635841e+05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.855245e+07,NaN
std,5.957691e+05,NaN,7.276045e+04,9.091231e+02,5.223984e+04,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.856277e+06,NaN
min,1.877580e+05,NaN,2.000000e+01,1.000000e+00,1.000000e+00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.731030e+05,NaN
25%,4.129660e+07,NaN,7.478500e+04,4.110000e+02,1.798230e+05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.021406e+07,NaN
50%,4.159092e+07,NaN,1.382520e+05,1.224000e+03,1.802210e+05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.058549e+07,NaN
75%,4.188519e+07,NaN,1.976830e+05,1.925000e+03,1.807170e+05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.091176e+07,NaN
max,4.218016e+07,NaN,2.577670e+05,3.580000e+03,2.405810e+05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.131491e+07,NaN